name: The Sessions
favicon: null
layout_spectrum: 0.14336774684488773
typography_spectrum: 0.722253869753331
title: a new party experience in brussels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e2ee'
    - '#a8b4ca'
    - '#8b9cb0'
    - '#696742'
    - '#252122'
  brandStrength: 0.3125
  lightness: 0.035189680522307754
  saturation: 0.4459031892474741
  rhythmicContrast: 0.75
purpose: []
